
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const DealSizeInfo: React.FC = () => {
  return (
    <div className="container mx-auto px-4 py-8">
      <Card className="calculator-card">
        <CardHeader>
          <CardTitle className="text-2xl text-primary">Understanding Average Deal Size</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-green max-w-none">
          <h2 className="text-xl font-semibold text-primary mt-4 mb-2">What is Average Deal Size?</h2>
          <p className="mb-4">
            Average Deal Size is a critical sales metric that measures the average value of closed-won deals within a specific period. 
            It is calculated by dividing the total revenue generated by the total number of deals. This key performance indicator (KPI)
            offers valuable insights into your sales process, customer acquisition strategy, and overall business health.
          </p>
          
          <h2 className="text-xl font-semibold text-primary mt-6 mb-2">Why is Average Deal Size Important for CRM Teams?</h2>
          <p className="mb-4">
            For CRM teams, tracking and optimizing average deal size is crucial for several reasons:
          </p>
          
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>
              <strong className="font-medium">Revenue Forecasting:</strong> Understanding your average deal size helps in creating more accurate sales forecasts and revenue projections for your business.
            </li>
            <li>
              <strong className="font-medium">Resource Allocation:</strong> It guides decisions on where to allocate sales resources to maximize return on investment (ROI) and overall sales efficiency.
            </li>
            <li>
              <strong className="font-medium">Sales Strategy Refinement:</strong> Insights from deal size analysis enable teams to refine their targeting, pricing strategies, and value propositions.
            </li>
            <li>
              <strong className="font-medium">Performance Benchmarking:</strong> It provides a benchmark to measure individual sales rep performance and identify coaching opportunities.
            </li>
          </ul>
          
          <h2 className="text-xl font-semibold text-primary mt-6 mb-2">How to Improve Your Average Deal Size</h2>
          <p className="mb-4">
            Increasing your average deal size can significantly impact your revenue and profitability. Here are some effective strategies:
          </p>
          
          <ol className="list-decimal pl-6 mb-4 space-y-2">
            <li>
              <strong className="font-medium">Value-Based Selling:</strong> Focus on communicating the unique value proposition of your product or service rather than competing on price.
            </li>
            <li>
              <strong className="font-medium">Cross-Selling and Upselling:</strong> Train your sales team to identify opportunities for additional products or premium upgrades that add value to the customer.
            </li>
            <li>
              <strong className="font-medium">Target Enterprise Clients:</strong> Develop strategies to attract and nurture relationships with larger organizations that typically have bigger budgets.
            </li>
            <li>
              <strong className="font-medium">Bundle Products or Services:</strong> Create attractive packages that encourage customers to purchase more in a single transaction.
            </li>
            <li>
              <strong className="font-medium">Improve Sales Skills:</strong> Invest in training programs that enhance negotiation skills, objection handling, and consultative selling approaches.
            </li>
          </ol>
          
          <h2 className="text-xl font-semibold text-primary mt-6 mb-2">Interpreting Your Results</h2>
          <p className="mb-4">
            When analyzing your average deal size, consider these contextual factors:
          </p>
          
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>
              <strong className="font-medium">Industry Benchmarks:</strong> Compare your metrics against industry standards to understand your competitive positioning.
            </li>
            <li>
              <strong className="font-medium">Historical Trends:</strong> Track changes over time to identify patterns, seasonality, or the impact of strategic initiatives.
            </li>
            <li>
              <strong className="font-medium">Customer Segments:</strong> Break down average deal size by customer segment or vertical to identify your most valuable markets.
            </li>
            <li>
              <strong className="font-medium">Sales Cycle Length:</strong> Analyze the relationship between deal size and sales cycle duration to optimize your process.
            </li>
          </ul>
          
          <h2 className="text-xl font-semibold text-primary mt-6 mb-2">Using This Calculator</h2>
          <p className="mb-4">
            Our Average Deal Size Calculator offers a user-friendly interface to quickly calculate your average deal size and compare it with benchmarks. 
            Simply input your total revenue and number of deals to get instant insights. Additionally, the visualization tools help you understand your 
            performance at a glance and identify areas for improvement. Use the export features to share these insights with your team or include them in your reports.
          </p>
          
          <p className="text-sm text-gray-500 mt-8">
            Note: This calculator provides estimates based on the information you enter. For comprehensive financial advice, please consult with a professional financial advisor.
          </p>
        </CardContent>
      </Card>
    </div>
  );
};

export default DealSizeInfo;
